---
- name: Install LEMP stack
  hosts: localhost
  become: yes
  tasks:

   - name: Install nginx
     ansible.builtin.yum:
       name: nginx
       state: present

   - name: Start and enable nginx service
     ansible.builtin.service:
       name: nginx
       state: started
       enabled: true

   - name: Install mariadb
     ansible.builtin.yum:
       name: mariadb-server
       state: present

   - name: Start and enable mariadb service
     ansible.builtin.service:
       name: mariadb
       state: started
       enabled: true

   - name: Install php and php-fpm
     ansible.builtin.yum:
       name:
          - php
          - php-fpm
       state: present

   - name: Start and enable php-fpm service
     ansible.builtin.service:
       name: php-fpm
       state: started
       enabled: true

   - name: Deploy php application
     ansible.builtin.copy:
       dest: /usr/share/nginx/html/index.php
       content: "<?php phpinfo();?>"